### ISSUE TITLE
Turning the screen resets the app

### ISSUE THREAD

**Issue by bjoern-tantau** [randombits-dev/interval-timer#2] opened 2024-02-06 11:12 UTC
When I turn my screen while a timer is active it resets and starts from the beginning. And the text from the start screen is overlapping with the countdown.

![Screenshot_20240206-121014](https://github.com/randombits-dev/interval-timer/assets/8307357/2c466b48-a4c4-46a9-8610-b5b7b586a616)

Android 13 on a Fairphone 3.

**Comment by nienow** [comment] 2024-02-07 15:04
Thanks for reporting this, I have updated the app to be locked in portrait mode, since that is what it was designed for. It make take a couple days before Fdroid pulls the update.

**Comment by nienow** [comment] 2024-02-21 21:14
Fixed in v1.0.8

**Closed by nienow** 2024-02-21 21:14 UTC
